openwisp_notifications/models.py, openwisp_notifications/tests/test_notifications.py
This PR serves as a quick patch for truncated email subject.
Fixes #24 
_P.S. : These changes were already made in #19_
=> [email] Fixed truncated email subject #24

README.rst, openwisp_notifications/static/openwisp_notifications/css/notifications.css, openwisp_notifications/templatetags/openwisp_notifications.py, openwisp_notifications/tests/test_admin.py
Closes #28 
Closes #32 
This might be a better way to follow DRY principle, but I was not sure whether having function inside 
function is desirable. What are your thoughts? 
```
def test_non_zero_notifications(self):
def test_ui_notification_badge(obj, no_of_notifications):
for _ in range(no_of_notifications):
notify.send(**obj.notification_options)
r = obj.client.get(obj._url)
obj.assertContains(r, obj._expected_output(str(no_of_notifications)))
with self.subTest("Test UI for less than 100 notifications"):
test_ui_notification_badge(self, 10)
with self.subTest("Test UI for 99+ notifications"):
test_ui_notification_badge(self, 100)
```
Did some testing of UI as well. :smile: 
Desktop
Responsive
Desktop
Responsive
Desktop
Responsive
=> [ui] Fixed notification badge for 99+ notifications #28

.travis.yml, README.rst, docker-compose.yml, openwisp_notifications/base/models.py, openwisp_notifications/handlers.py, openwisp_notifications/tasks.py, openwisp_notifications/tests/test_notifications.py, openwisp_notifications/utils.py, requirements-test.txt, requirements.txt, tests/openwisp2/__init__.py, tests/openwisp2/celery.py, tests/openwisp2/settings.py
Closes #43 
Caveats:
1. Receiver is triggered for all objects and makes two queries to database each time.
2. If number of notifications is huge, than this can take time. 
I thought of offloading this work to a celery worker, but it will not be possible as related objects may  already get deleted even before celery worker can complete this task. And we will get an error at assigning description. 
If we strictly opt for deleting notifications, that task can be offloaded to celery workers easily.
We are preserving information by not deleting notifications and leaving it to user when to delete such notifications.
=> [models] Fixed bug for missing related object

README.rst, openwisp_notifications/base/models.py, openwisp_notifications/handlers.py, openwisp_notifications/settings.py, openwisp_notifications/templates/openwisp_notifications/email_template.html, openwisp_notifications/templatetags/notification_tags.py, openwisp_notifications/tests/test_admin.py, openwisp_notifications/tests/test_api.py, openwisp_notifications/tests/test_notifications.py, openwisp_notifications/utils.py
Added caching for related objects to limit database queries.
Closes #47 
For 18 notifications, 58 database queries were being made each time earlier on Notification Admin. After caching they are down to 4 . :smile: 
**Before**
**After**
=> [fix] Reduced database queries for notifications #47

openwisp_notifications/tests/test_api.py, openwisp_notifications/tests/test_notifications.py, tests/openwisp2/sample_notifications/tests/test_django.py, tests/openwisp2/urls.py
We have to force users to use the same URL namespace if we want the software to work as expected also when extended.
=> [chores] Made URL namespace consistent (2)

README.rst, openwisp_notifications/base/models.py, openwisp_notifications/handlers.py, openwisp_notifications/tests/test_notifications.py
Ensure extra data is passed when generating `message` and `email_subject`.
=> [feature] Allow passing extra data

openwisp_notifications/static/openwisp-notifications/css/notifications.css, openwisp_notifications/static/openwisp-notifications/js/notifications.js
- Increased spacing between each notification toast
- Ensure elements below the container are clickable
- Reordered z-index so that toasts are always shown in front,
while the notification widget is just below, but higher
than the navigationg menu
- doubled the amount of time toasts will stay visible before
disappearing automatically
Related to #94
Here's how it looks:
=> [ux] Improved notifications toast #94

openwisp_notifications/base/forms.py, openwisp_notifications/tests/test_admin.py
Fixed NotificationSettingInlineAdmin for view only access,
i.e. when admin of an organization view UserAdmin of other
users of same organization.
=> [fix] Fixed Notification Setting Inline Admin

openwisp_notifications/static/openwisp-notifications/css/notifications.css
The issue was related to div having class ".ow-notifications". It was taking css property bottom=-1 and it was positioned absolutely that's why it was taking complete height. So it made bottom = auto.
Fixes #130
=> [fix] Fixed transparent element of notification widget that covered page #130

openwisp_notifications/static/openwisp-notifications/js/object-notifications.js
The required feature has been added to close the object notification widget on clicking the escape button from the keyboard and focus also returns to the "UNSUBSCRIBE" button.
Fixes #133
=> [Fix] Added escape key handler for object notification widget #133 

README.rst, openwisp_notifications/handlers.py, openwisp_notifications/management/commands/__init__.py, openwisp_notifications/management/commands/populate_notification_preferences.py, openwisp_notifications/tests/test_notifications.py, openwisp_notifications/tests/test_utils.py, tests/openwisp2/sample_notifications/management/commands/create_notification.py, tests/openwisp2/sample_notifications/management/commands/populate_notification_preferences.py, tests/openwisp2/sample_notifications/tests/test_django.py, tests/openwisp2/settings.py
Solution:
- Decreased max_retry_limit for celery tasks
- Added error handling for the error thrown by celery for broker being unreachable
- Added logger to notify errror to the user and provide information on resolving the error
Note:
- An active bug in celery does not let the developer to selectively set max_retry_limit for a particular task.
See https://github.com/celery/celery/issues/4627
- In this patch, a workaround is implemented which sets the global max_rety_limit. This decreases max_retry_limit for every task.
Fixes #142
=> [fix] Fixed stalling of migrate command when celery broker is unreachable #142

openwisp_notifications/static/openwisp-notifications/js/notifications.js
In this solution, I am making use of localStorage in such a way that I am creating different IDs for different tabs and windows of a browser and storing it in the "windows" variable in localStorage. Whenever a notification comes I give access to play the sound to the window/tab whose ID comes first in the "windows" variable. Also removing its ID from the variable on page reload or close.
Fixes #137
=> [fix] Fixed playing sound from multiple windows #137

openwisp_notifications/tests/test_websockets.py, requirements-test.txt, requirements.txt
Bug:
Tests for websockers were importing ASGI application router object from
test project files. This implementation will break if tests are in
another project.
Fix:
Imported the ASGI application router usin string from settings object
Refs https://github.com/openwisp/openwisp-controller/pull/316#discussion_r517749794
=> [fix] Fixed compatible versioning in dependencies and tests for websockets

README.rst, openwisp_notifications/templates/admin/base_site.html, openwisp_notifications/tests/test_admin.py
The patch uses the django-loci-module approach in ```base_site.html``` to restrict wss connection attempts while the application is being run over http. The section on IP address additions to ```ALLOWED_HOSTS``` in settings module has been removed from  ```README.rst```. The relevant test in ```test_admin.py``` has been removed.
Fixes #160
=> [fix] Fix wss connection error when running on http #160

openwisp_notifications/templates/admin/base_site.html
Avoid including jquery if block.super already includes it
=> [fix] Avoid multiple jquery inclusions in base_site.html

openwisp_notifications/static/openwisp-notifications/css/notifications.css
This commit fixes the bell icon after changes from https://github.com/openwisp/openwisp-utils/pull/182
Before:
https://user-images.githubusercontent.com/7120526/114720743-934da200-9d38-11eb-9c49-21b4709eb5a1.mp4
After:
https://user-images.githubusercontent.com/7120526/114720765-96e12900-9d38-11eb-8a8a-08be811ce762.mp4
=> [ux] Fix notification icon

README.rst, requirements-test.txt, requirements.txt
We need this if we want to allow using the master branch in staging systems without failures.
Without this, when installing this module, the older versions of openwisp-users and openwisp-utils will be installed.
=> [deps] Updated OpenWISP dependencies to current dev versions

openwisp_notifications/static/openwisp-notifications/js/notifications.js
Notification toast will close and flag notification as read
even if notification widget is still reloading.
Closes #211
=> [fix] Fixed closing notification toast on slow connections #211

requirements.txt, tests/openwisp2/settings.py
The issue required updation to celery version 5. From my findings, it mainly required updating the celery version ```requirements.txt``` to ```celery~=5.0.5```, which has been done in this patch. According to the documentation for celery 5.0, the settings have been changed to lowercase keys. However, in consistence with the rest of the codebase, this patch continues using the uppercase keys for settings with the use of appropriate namespaces. 
Using this [update](https://docs.celeryproject.org/en/stable/whatsnew-5.0.html#removed-deprecated-modules) as a reference, I have removed the ```celery.task``` logger in ```tests/settings.py```. It has been just commented out for the time-being and I wish to take reviewers' opinions about whether or not to completely delete the logger. 
The new CLI …
=> [deps] Update Celery to version 5 #155

openwisp_notifications/api/views.py
- Fixed browsable API view for NotificationReadAllView
- Moved updating database query to celery worker
=> [fix] Fixed NotificationReadAllView 

openwisp_notifications/handlers.py, openwisp_notifications/tests/test_notifications.py
Added exception handling for the issue #179 and test for the same . So ,If throws exception the function will be returned empty and mail will not be sent.
=> [Fix] Error handling send email notification #179

openwisp_notifications/tests/test_admin.py
Check for the default organization instead of default notification type,
Fixes #157
=> [fix] Project dependent test cases #157

openwisp_notifications/static/openwisp-notifications/css/object-notifications.css
- Reduced `bell-icon` height, removed redundant flex property from `.ow-object-notify`
Fixes #219
=> [fix] Unsubscribe button alignment #219

openwisp_notifications/api/views.py
=> [fix] Swagger api doc issue

CHANGES.rst, openwisp_notifications/__init__.py
-   Fixed [hardcoded static image URLs][]. These created issues when
static files are served using an external service (e.g. S3 storage
buckets).
-   Fixed ["Organization.DoesNotExist" error on creating a new
organization][].
[hardcoded static image URLs]: https://github.com/openwisp/openwisp-notifications/issues/243
["Organization.DoesNotExist" error on creating a new organization]: https://github.com/openwisp/openwisp-notifications/issues/238
=> 1.0.2 release

README.rst, tests/openwisp2/settings.py
We have recently added admin autocomplete filters to various OpenWISP modules, including `openwisp-users`. Therefore, we need to add **'admin_auto_filters'** to **INSTALLED_APPS** so that Django can locate the correct filter template location.
=> [fix] Fixed TemplateDoesNotExist admin error

openwisp_notifications/templates/admin/base_site.html
The library re-connects if it fails to establish a connection in "timeoutInterval". On slow internet connections, the default value of "timeoutInterval" will keep terminating and re-establishing the connection.
**Related**
- https://github.com/openwisp/openwisp-controller/pull/773
=> [fix] Increased "timeoutInterval" for ReconnectingWebSocket

openwisp_notifications/tasks.py, openwisp_notifications/tests/test_api.py, openwisp_notifications/tests/test_helpers.py, openwisp_notifications/tests/test_ignore_object_notification.py, openwisp_notifications/tests/test_notification_setting.py, openwisp_notifications/tests/test_notifications.py, openwisp_notifications/tests/test_utils.py, tests/openwisp2/sample_notifications/apps.py
Mock NOTIFICATION_TYPE and NOTIFICATION_CHOICES to avoid polluting the test environment from notification types registered in the test.
=> [tests] Fixed tests that polluted the test environment

openwisp_notifications/handlers.py, openwisp_notifications/tests/test_notifications.py
If a user is in several organizations,
they will receive multiple identical notifications. The reason for this is that the database query,
which determines which user should receive the notification, does a LEFT OUTER JOIN with the "openwisp_users_organizationuser" table. In this table, a user is multiple times listed,
when he is in several organizations.
Therefore the query returns such a user multiple times, which will then receive multiple identical notifications. This commit fixes this bug by adding a distinct to all user queries.
Fixes #277
=> [fix] Prevent sending multiple identical notifications #277

README.rst, openwisp_notifications/api/serializers.py, openwisp_notifications/base/models.py, openwisp_notifications/handlers.py, openwisp_notifications/static/openwisp-notifications/css/notifications.css, openwisp_notifications/static/openwisp-notifications/js/notifications.js, openwisp_notifications/templates/admin/base_site.html, openwisp_notifications/tests/test_api.py, openwisp_notifications/tests/test_notifications.py, openwisp_notifications/tests/test_widget.py, openwisp_notifications/types.py
=> [feature] Added generic message notification type (shown in dialg box)

openwisp_notifications/base/models.py, openwisp_notifications/checks.py, openwisp_notifications/context_processors.py, openwisp_notifications/settings.py, openwisp_notifications/tests/test_admin.py, openwisp_notifications/tests/test_notifications.py, openwisp_notifications/tests/test_utils.py
Maintain consistency with other modules by shortening the internal naming for the django settings of this module.
=> [chores] Shortened internal settings for consistency

README.rst, openwisp_notifications/base/models.py, openwisp_notifications/handlers.py, openwisp_notifications/settings.py, openwisp_notifications/static/openwisp-notifications/js/notifications.js, openwisp_notifications/tasks.py, openwisp_notifications/templates/emails/batch_email.html, openwisp_notifications/templates/emails/batch_email.txt, openwisp_notifications/tests/test_notifications.py, openwisp_notifications/utils.py
=> [feature] Batch email notifications

openwisp_notifications/handlers.py, openwisp_notifications/tasks.py, openwisp_notifications/tests/test_notification_setting.py
=> [fix] Fixed unnecessary triggering of celery tasks #283

openwisp_notifications/migrations/0009_alter_notificationsetting_organization_and_more.py
- N/A I have written new test cases for new code and/or updated existing tests for changes to existing code.
- N/A I have updated the documentation.
The migration file 0009_alter_notificationsetting_organization_and_more was not taking into account swappable models.
=> [chores/fix] Fixed unswappable migration

openwisp_notifications/api/serializers.py, openwisp_notifications/tests/test_api.py, openwisp_notifications/tests/test_selenium.py
Fixes #351
The notification prefences API would return
`NotificationSetting.web_notification` for the `web` field and `NotificationSetting.email_notification` for the `email` field.
These methods returns the fallback value from the notification type configuration, when the database contains `None`.
=> [fix] Notification preferences API returns fallback value if None #351

openwisp_notifications/base/models.py, openwisp_notifications/handlers.py, openwisp_notifications/tests/test_views.py
… are disabled #343
Updated the check_email_verification function to check the email boolean value before sending email verification notification. Tested by creating 2 separate users with opposite boolean values and if email=True (email notification enabled) then only user is prompted with notification, else restrained.
Fixes #343
Closes #343.
As mentioned in the issue, the check_email_verification function was updated to ensure that only is email boolean value is true (email notifications are enabled) then only user gets prompted for verification. Updated towards class method for better readability. Tests were written as mentioned and manual checking was done by simulating 2 users with different email boolean values.
=> [chores] Avoid email notification warning if email notifications are disabled

openwisp_notifications/static/openwisp-notifications/js/preferences.js
AJAX requests should include credentials when API is hosted on a separate host (docker-openwisp).
=> [fix] Send credentials in async requests (preferences.js)

openwisp_notifications/api/views.py, openwisp_notifications/tests/test_api.py, openwisp_notifications/tests/test_notification_setting.py
Filtered out notification settings linked to disabled organizations by modifying the queryset. Added a test to ensure preferences from inactive organizations are excluded from user settings.
Fixes #366
- N/A I have updated the documentation.
Closes #366
Updated the queryset to exclude notification settings from inactive organizations. Implemented a test to verify that user preferences tied to disabled organizations are not returned.
=> [fix] Hide notification preferences for disabled orgs #366

openwisp_notifications/tests/test_admin.py, openwisp_notifications/tests/test_notifications.py
Solves part of #369 . More changes seems required...
I set `user_app_label` to `"openwisp_users"` in TestCases that required it.
The same way I saw it done in controller and other modules...
I think this is the first step to avoid copy-pasting too much test code when extending `openwisp-users` and `openwisp-notifications`
=> [fix:tests] Allow overriding users app_label in tests

tests/openwisp2/settings.py
It seems the setting `TEMPLATE[0]["DIRS"]` is unnecessary, since we are using loaders to resolve templates.
Also looking at [the docs] (https://docs.djangoproject.com/en/5.2/howto/overriding-templates/#overriding-from-the-project-s-templates-directory) it seems this setting does not apply to the current situation (django project template override vs extended app template)
And finally, imho, it makes it even harder to understand  what one needs to do to write an `openwisp-notifications-extended` app with templates that work as expected...
I removed that setting on my machine and tests still pass... But I m not used to django and might have misunderstood something ? or it might be something needed for an old version of django only ?
=> [change] Remove unnecessary TEMPLATE DIRS in settings.py

openwisp_notifications/templates/admin/base_site.html, openwisp_notifications/templatetags/notification_tags.py, openwisp_notifications/tests/test_base_site_override.py
Closes #271 
Restrict notification widget to admin and notification preferences page only
=> [fix] Restrict notification widget to admin and notification preferences page only

docs/user/web-email-notifications.rst, openwisp_notifications/tests/test_notifications.py, openwisp_notifications/utils.py
Closes #396
If there's only one notification in the batch, use the Notification.email_subject for the email subject and title.
=> [change] Batch email notification: restore single notification email #396

openwisp_notifications/settings.py
Bug:
The `openwisp_notifications.settings.get_setting` function was not reading the value from Django settings. Thus, it was not using the setting defined in the Django projects.
=> [fix] Corrected get_setting function to properly retrieve settings
