openwisp_notifications/admin.py
openwisp_notifications/base/admin.py
openwisp_notifications/tests/test_admin.py

Abstracted code of Admin Class.
Added links to related object.
Added changes from https://github.com/openwisp/openwisp-monitoring/pull/40

[admin] Abstracted code for Admin

---

openwisp_notifications/handlers.py
openwisp_notifications/tests/test_notifications.py

If the recipient is not provided in the argument, superusers and staff users of an organization related to the target object will be implicitly added as recipients.
The changes have been made with the goal to allow Group, Query-set, or an object as a recipient. In the case of a Group, only those users will be notified which are from the same organization as the target object.

[orgs] Added option to have organization staff users as reciepient

---

.travis.yml
CONTRIBUTING.rst
LICENSE
README.rst
openwisp_notifications/base/admin.py
openwisp_notifications/tests/test_admin.py
run-qa-checks

Added LICENSE and CONTRIBUTING.rst
Minor bug fix in admin for displaying notifications.
Updated travis for using openwisp-utils development version.
Fixes #11

[docs] Added README

---

MANIFEST.in
openwisp_notifications/handlers.py
openwisp_notifications/static/openwisp_notifications/css/notifications.css
openwisp_notifications/templates/admin/base.html
openwisp_notifications/tests/test_admin.py
openwisp_notifications/tests/test_notifications.py
tests/settings.py

Fixed #15 and added tests to cover more cases.
Added `MANIFEST.in`
Added `base.__init__.py`

[minor] Fixed recipients in notify handler

---

.travis.yml
requirements.txt

[setup] Pinned versions of dependencies #21

---

README.rst
openwisp_notifications/apps.py
openwisp_notifications/base/admin.py
openwisp_notifications/handlers.py
openwisp_notifications/migrations/0003_notification_notification_type.py
openwisp_notifications/models.py
openwisp_notifications/settings.py
openwisp_notifications/templates/openwisp_notifications/default_message.md
openwisp_notifications/tests/test_admin.py
openwisp_notifications/tests/test_notifications.py
openwisp_notifications/types.py
setup.cfg

- Added configurable notification types
- Added configurable message template
- Updated README and added tests
Related to #1

[notification] Add notification type setting

---

README.rst
openwisp_notifications/management/commands/__init__.py
openwisp_notifications/management/commands/create_notification.py
openwisp_notifications/tests/test_utils.py
tests/openwisp2/sample_notifications/apps.py

Added documentation for creating notification in sample app. Continuation of #46
Closes #54
Added management command for creating dummy notification.

[qa] Added improvements for simplifying manual testing

---

.jshintrc
README.rst
openwisp_notifications/apps.py
openwisp_notifications/checks.py
openwisp_notifications/context_processors.py
openwisp_notifications/settings.py
openwisp_notifications/static/openwisp_notifications/js/notifications.js
openwisp_notifications/templates/admin/base_site.html
openwisp_notifications/tests/test_admin.py
openwisp_notifications/tests/test_utils.py
requirements-test.txt
tests/openwisp2/settings.py

Added configurable hosts for API
Added configurable notification sound for API
Closes #9

[feature] Added configurable settings for JS widget

---

README.rst
openwisp_notifications/tests/test_api.py
openwisp_notifications/urls.py

For consistency with other openwisp modules.

[chores] Simplified URL namespace

---

openwisp_notifications/static/openwisp_notifications/js/notifications.js
openwisp_notifications/templates/admin/base_site.html
openwisp_notifications/tests/test_admin.py

Removed loading websockets if user is not authenticated
Refactored jQuery imports.
Closes #70 
Closes #72

[fix] Fixed JS bugs on admin site #70 #72

---

.jshintrc
openwisp_notifications/static/openwisp_notifications/js/notifications.js
openwisp_notifications/templates/admin/base_site.html
openwisp_notifications/tests/test_admin.py
tests/openwisp2/settings.py

[fix] Web Socket protocol on production environment #77

---

README.rst
openwisp_notifications/api/serializers.py
openwisp_notifications/base/models.py
openwisp_notifications/exceptions.py
openwisp_notifications/handlers.py
openwisp_notifications/static/openwisp_notifications/css/notifications.css
openwisp_notifications/static/openwisp_notifications/js/notifications.js
openwisp_notifications/tasks.py
openwisp_notifications/tests/test_api.py
openwisp_notifications/tests/test_notifications.py
openwisp_notifications/utils.py
openwisp_notifications/websockets/handlers.py

Notifications missing any required related object will not be displayed
in notification widget.

[fix] Removed rendering of incomplete notifications #50

---

openwisp_notifications/tests/test_admin.py
openwisp_notifications/tests/test_api.py
openwisp_notifications/tests/test_notifications.py
tests/openwisp2/settings.py

[enhancement] Added TimeLoggingTestRunner from openwisp_utils

---

openwisp_notifications/api/serializers.py
openwisp_notifications/api/urls.py
openwisp_notifications/api/views.py
openwisp_notifications/base/models.py
openwisp_notifications/handlers.py
openwisp_notifications/static/openwisp-notifications/js/notifications.js
openwisp_notifications/templates/openwisp_notifications/email_template.html
openwisp_notifications/tests/test_api.py
openwisp_notifications/tests/test_notifications.py

[enhancement] Added redirect view for marking notification as read

---

openwisp_notifications/static/openwisp-notifications/css/notifications.css
openwisp_notifications/static/openwisp-notifications/js/notifications.js

- improved readability of notification date and time
- fixed JS issue when clicking on unread items
- changed colors to be more neutral

[ux] Improvements to notification widget

---

openwisp_notifications/api/views.py
openwisp_notifications/static/openwisp-notifications/css/notifications.css
openwisp_notifications/static/openwisp-notifications/js/notifications.js
openwisp_notifications/tests/test_api.py
openwisp_notifications/utils.py

Fixed unscrollable notification widget at higher resolution
Removed flagging notification based on intersection with visible document
Added flagging notifications based on mouseout event
Fixed using https in development server
Closes #91

[fix] Fixed notification widget

---

openwisp_notifications/tasks.py
openwisp_notifications/tests/test_notifications.py

Handled case where ContentType for deleted object is not available(deleted),
Closes #85

[fix] Fixed "delete_obsolete_notifications" celery task #85

---

openwisp_notifications/management/commands/__init__.py
openwisp_notifications/static/openwisp-notifications/js/notifications.js

Clicking on close button, opened target object link.
Fixed it by stopping propagation of click event.
Continuation of #97

[fix] Fixed notification toast

---

openwisp_notifications/static/openwisp-notifications/css/notifications.css
openwisp_notifications/static/openwisp-notifications/js/notifications.js
openwisp_notifications/templatetags/notification_tags.py

Fixed loader not shown while fetching more notifications.
Closes #96

[fix] Fixed notification widget loader #96

---

README.rst
openwisp_notifications/tasks.py
openwisp_notifications/tests/test_notifications.py
tests/openwisp2/settings.py

Added celery tasks for deleting notifications older than
pre-configured number of days, defaults to 90.
Closes #6

[feature] Added scheduled deletion of old notifications #6

---

openwisp_notifications/static/openwisp-notifications/js/notifications.js

API call to fetch notification is only made when user interacts
with notification widget(clicks bell icon).
Closes #100

[enhancement] Load notification on user interaction #100

---

README.rst
openwisp_notifications/management/commands/__init__.py
openwisp_notifications/migrations/0004_notificationsetting.py
tests/openwisp2/sample_notifications/migrations/0001_initial.py
tests/openwisp2/sample_notifications/migrations/0002_testapp.py
tests/openwisp2/sample_notifications/models.py
tests/openwisp2/sample_notifications/tests/test_django.py

[refactor] Removed importing concrete models #95

---

openwisp_notifications/handlers.py
openwisp_notifications/tests/test_notifications.py

- Fixed notifications should not be sent to inactive users
- Fixed notifications should not be sent to organization users who
are not organization admin
Closes #86
Closes #113

[fix] Fixed recipients queries for sending notifications #86 #113

---

openwisp_notifications/static/openwisp-notifications/css/notifications.css

[change] UX: changed style of notification widget buttons

---

.travis.yml
openwisp_notifications/tests/test_admin.py

Tested UI manually
Closes #121

[deps] Added support for Django~=3.1 #121

---

.travis.yml
openwisp_notifications/static/openwisp-notifications/css/notifications.css
openwisp_notifications/static/openwisp-notifications/js/notifications.js
openwisp_notifications/templates/admin/base_site.html
openwisp_notifications/templatetags/notification_tags.py
openwisp_notifications/tests/test_admin.py
tests/openwisp2/sample_notifications/templates/admin/base_site.html

Fixed notification bell and notification element not accessible from keyboard.
Added handlers for key events.
Closes #122

[fix] Fixed accessibility issues of notification widget #122

---

openwisp_notifications/templates/admin/change_form.html
openwisp_notifications/tests/test_admin.py

Ensured ignore notification widget JS written in
"admin/change_form.html" only loads for change view of ModelAdmin
Closes #128

[fix] Fixed ignore notification widget JS loading on add view #128

---

CHANGES.rst
openwisp_notifications/__init__.py

0.2.1 release

---

openwisp_notifications/tests/test_api.py
openwisp_notifications/tests/test_notifications.py
requirements-test.txt
requirements.txt

- Redirected noisy test output using utilities from openwisp-utils
**Blocked by**

[deps] Upgraded openwips-utils~=0.7.0

---

.github/workflows/build.yml

[chores] Droped support for Django 2.2 #135

---

openwisp_notifications/templates/admin/base_site.html
openwisp_notifications/tests/test_admin.py

- removed type="text/javascript" which in HTML5 is not needed
- added required alt attribute to bell icon

[chores] Minor fixes to HTML

---

.gitignore
openwisp_notifications/handlers.py
openwisp_notifications/migrations/0002_default_permissions.py
openwisp_notifications/migrations/0004_notificationsetting.py
openwisp_notifications/migrations/__init__.py

Need for this PR arose from https://github.com/openwisp/openwisp-controller/pull/390 where some bugs hurting extensibility of openwisp-users were found.

[fix] Fixed extensibility of openwisp-users

---

.github/workflows/build.yml

Fixed CI
relate to https://github.com/openwisp/openwisp-controller/issues/417

[ci] Fixed CI build for django~=3.0.0

---

openwisp_notifications/static/openwisp-notifications/css/notifications.css
openwisp_notifications/static/openwisp-notifications/css/object-notifications.css
openwisp_notifications/static/openwisp-notifications/js/notifications.js
openwisp_notifications/static/openwisp-notifications/js/object-notifications.js

##Fixed following issues:
- Removed event propagation stop when the document is clicked.
- Unsubscribe widget always remains open.
- Unsubscribe button was not having icon.
- Focus css was not working on both buttons.
- Unsubscribe button was getting skipped when pressing tab.
**Depends on**
https://github.com/openwisp/openwisp-utils/pull/226

[fix] Fixed minor issues

---

openwisp_notifications/static/openwisp-notifications/css/notifications.css
openwisp_notifications/static/openwisp-notifications/js/notifications.js
openwisp_notifications/templates/admin/base_site.html

Did some improvements in the active and hover effect of the notifications button. 
-  Icons color were not same.
- Focus on button was having some issues.
- Background of button on hover was transparent.

[fix] Fixed active and hover effect of notifications button

---

README.rst
openwisp_notifications/handlers.py
openwisp_notifications/tests/test_helpers.py
openwisp_notifications/tests/test_ignore_object_notification.py
openwisp_notifications/tests/test_notifications.py
openwisp_notifications/types.py

- delete_obsolete_objects task will excuted for models that are
mentioned in the models list
Closes #163

[change] Added "models" parameter to register_notification_type #163

---

README.rst
openwisp_notifications/handlers.py
openwisp_notifications/settings.py
openwisp_notifications/tests/test_websockets.py
openwisp_notifications/websockets/consumers.py
openwisp_notifications/websockets/handlers.py
requirements-test.txt

[fix] Fixed notification storm in UI #183

---

openwisp_notifications/websockets/consumers.py
openwisp_notifications/websockets/handlers.py
tests/openwisp2/settings.py

Updated test project settings for CHANNEL_LAYERS
Closes #210

[refactor] Added dedicated channel layer group for each user #210

---

.github/workflows/build.yml
openwisp_notifications/apps.py
openwisp_notifications/base/models.py
openwisp_notifications/signals.py
requirements.txt
tests/openwisp2/sample_notifications/signals.py

Closes #194
Depends  on https://github.com/django-notifications/django-notifications/pull/323

[deps] Added support for Django 3.2 and 4.0 #194

---

openwisp_notifications/tasks.py
requirements.txt

[change] Added celery time limits to tasks #217 

---

openwisp_notifications/api/views.py

[Fix] Swagger api doc issues #169

---

README.rst
openwisp_notifications/static/openwisp-notifications/js/notifications.js
openwisp_notifications/static/openwisp-notifications/js/object-notifications.js
openwisp_notifications/urls.py

[change!] Made API url structure consistent with other OpenWISP modules #230

---

openwisp_notifications/management/commands/__init__.py
openwisp_notifications/tests/test_utils.py

Fixed receiving Notification even when disabled during development
Fixes #159

[fix] Notification when disabled during developement #159

---

README.rst
tests/openwisp2/settings.py

- Updated links of GIFs in `README`.
- Moved down rest_framework and drf_yasg order in `INSTALLED_APPS` to
make sure new theme must apply on API pages.
Closes #233

[docs] Updated screenshots and GIFs links #233

---

openwisp_notifications/static/openwisp-notifications/css/object-notifications.css

[fix] Fixed hardcoded static image URLs in object-notification.css #243

---

CHANGES.rst

(cherry picked from commit 9ff2a6faadcf5219d34c7c899253091ed075ff4e)

[docs] Updated changelog for 1.0.2 release

---

CHANGES.rst

(cherry picked from commit 6e3309c3783837fde1754ad5ec66891624c336cf)

[docs] Added changelog for 1.0.3 release

---

README.rst
openwisp_notifications/api/filters.py
openwisp_notifications/api/views.py
openwisp_notifications/tests/test_api.py

[change:api] Migrated to openwisp-users REST API filters #260

---

.coveragerc
.github/workflows/build.yml
openwisp_notifications/__init__.py
openwisp_notifications/migrations/0001_initial.py
openwisp_notifications/templatetags/notification_tags.py
openwisp_notifications/tests/test_admin.py
requirements-test.txt
requirements.txt
setup.py
tests/openwisp2/sample_notifications/__init__.py
tests/openwisp2/sample_notifications/apps.py
tests/openwisp2/sample_notifications/migrations/0001_initial.py

- Dropped support for Python 3.7
- Bumped django-notifications-hq~=1.8.2
- Bumped markdown~=3.4.3

[deps] Added support for Django 4.1.0 and Django 4.2.0

---

openwisp_notifications/handlers.py
openwisp_notifications/tests/test_notifications.py

[change] Do not send email notifications to unverified email addresses

---

openwisp_notifications/tests/test_admin.py

Related to:
https://github.com/openwisp/openwisp-users/commit/99d16adf8991c0e2af45d6939844080d811bbd99

[tests] Updated tests due to openwisp-users base class reorganization

---

.github/workflows/build.yml

[ci] Run tests even on QA fails

---

.github/workflows/build.yml
openwisp_notifications/base/forms.py

Reformatted, updated CI, cache pip deps.

[qa/ci] Reformatted, updated CI, cache pip deps

---

pyproject.toml

Fixed configuration to track websocket coverage

[chores] Fixed configuration to track websocket coverage

---

openwisp_notifications/tests/test_api.py

Added support for djangorestframework<=3.15.1

[deps] Added compatibility for djangorestframework<=3.15.1

---

.github/workflows/version-branch.yml
CHANGES.rst
openwisp_notifications/__init__.py
requirements-test.txt
requirements.txt

[ci] Added GitHub workflow to replicate commits to version branch

---

openwisp_notifications/handlers.py
openwisp_notifications/tasks.py
openwisp_notifications/tests/test_notification_setting.py

[change] Removed deprecated code for updating superuser notification settings #283

---

.github/workflows/pypi.yml

[skip ci] Fixed URL in PyPI release action

---

.github/workflows/build.yml
openwisp_notifications/tests/test_selenium.py

[tests] Made selenium tests resilient to failures

---

openwisp_notifications/static/openwisp-notifications/js/notifications.js
openwisp_notifications/tests/test_helpers.py
openwisp_notifications/tests/test_notifications.py
openwisp_notifications/tests/test_selenium.py

[fix] Notification widget removing URL fragment

---

docs/user/sending-notifications.rst
openwisp_notifications/base/models.py
openwisp_notifications/base/notifications.py
openwisp_notifications/settings.py
requirements.txt

[change] Drop dependency on django-notifications #353

---

openwisp_notifications/api/views.py
openwisp_notifications/settings.py
openwisp_notifications/tests/test_api.py
openwisp_notifications/tests/test_notifications.py
openwisp_notifications/tests/test_selenium.py

[change] Disallow changing preferences for generic messages #359

---

openwisp_notifications/static/openwisp-notifications/css/unsubscribe.css
openwisp_notifications/templates/openwisp_notifications/unsubscribe.html

[change] Made overriding logo in unsubscribe page easier

---

.github/workflows/build.yml
openwisp_notifications/templates/openwisp_notifications/emails/notification.html
openwisp_notifications/tests/__init__.py
openwisp_notifications/tests/test_notifications.py

- N/A I have updated the documentation.
Closes #393
**Blockers**

[chores:ui] Improved notification email template on narrow screens #393

---

.github/workflows/build.yml
openwisp_notifications/tests/test_admin.py
openwisp_notifications/tests/test_helpers.py
openwisp_notifications/tests/test_selenium.py
openwisp_notifications/tests/test_users_integration.py

[tests] Included user integration tests
